import { resolve } from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { doors, serves } from 'kehikot-module-protocol/serve'

import { BUILD, MANIFEST, answer } from './doors.ts'
import { ID, PREFERRED_PORT } from './manifest.ts'

/**
 * The doors this app answers on are `doors()` from the protocol, served by the
 * one process that serves the page: the manifest at its well-known path, the
 * page (generated, with this process's build printed into it, `no-store`,
 * `frame-ancestors`) at `/`, and the health check through `answer` in
 * `doors.ts`. See the protocol's docs/module-plumbing.md.
 *
 * A module is ONE ORIGIN or it is nothing: the protocol refuses a manifest
 * whose `entry` points anywhere but the origin that served the manifest. So the
 * manifest, the health check and the page cannot be split across two processes
 * on two ports, however tidy that would be.
 *
 * ## Who may frame this page, and the stub host
 *
 * This module declares storage, so a host frames it WITH `allow-same-origin`
 * and it keeps its real origin. Having an origin is what makes
 * `frame-ancestors` mean something: without it any page anywhere could frame
 * this one. `doors()` sends the header from `frameAncestors()` — whoever runs
 * this decides, through `KEHIKOT_ORIGINS`, and the default is every address a
 * host in this workspace actually serves on.
 *
 * `127.0.0.1:7821` is added to whatever that says, and it is the stub host in
 * `dev/stub-host.ts`. That was not planned: the first time this page was
 * measured in a browser after the header was added, the frame did not load at
 * all and the probe reported "no module frame" at every width, with nothing in
 * any log — because a refused frame is refused by the browser and this app
 * never hears about it. A development harness that silently stops working the
 * moment somebody adds a security header is a harness people stop trusting, so
 * the one loopback port it runs on is named, as `ancestors` on `doors()`.
 */
const STUB_HOST = 'http://127.0.0.1:7821'

/** `/health` beside the protocol's own three: see `answer` in `doors.ts`. */
const ours = (path: string) => path === '/healthz' || path === '/health' || path === '/mcp' || path.startsWith('/api/')

/**
 * The dev server, and the one line in it that decides who may read this port.
 *
 * There is no `build` here and no `build` script: the page is generated by
 * `doors()`, so there is no `index.html` for Rollup to start from, and nothing
 * serves a `dist/` — see `run.sh`.
 *
 * ## `server.cors: false`, and why this file used to say the opposite
 *
 * It said `cors: true`, and it had to, and the reasoning was correct for the app
 * that existed then. A host frames a module WITHOUT `allow-same-origin` unless
 * its manifest declares storage, which puts the page on an opaque origin — and
 * `<script type="module">` is ALWAYS fetched in CORS mode, so with no permissive
 * header not one script in the page runs. The document loads, `load` fires, the
 * host greets it, and nothing answers. `curl` cannot see it, being unsubject to
 * CORS; only the browser console can. That has cost this codebase days, and the
 * paragraph is kept rather than deleted because the trap is still there for
 * anybody who removes `storage: true` from the manifest without reading this.
 *
 * What changed is that this app had something behind a door for a while:
 * `/api/references` ran `gh issue list` under this machine's login, in a folder
 * a caller named, and with a permissive `Access-Control-Allow-Origin` any page in
 * any tab could have read the answer. That door is gone — the rows are the
 * host's shared tracker reading now (issue #4) — but the arrangement that shut
 * it stays, because it costs nothing and the next door anybody adds here
 * inherits it: the manifest declares `storage: true`, this page keeps a real
 * origin, its scripts are ordinary same-origin requests, and no CORS is
 * involved at all. The full argument is in `manifest.ts`.
 *
 * `false` rather than simply omitted, and the word is earned: Vite's default is
 * not "off". It answers CORS for any loopback origin, so the remote-website hole
 * is shut by Vite and the local one is not — and nothing this server answers
 * should be readable by every other dev server somebody happens to be running. Turning it off costs this page nothing, because everything it
 * fetches is its own origin.
 *
 * The check, which takes one line and should be run after touching this file:
 *
 *   curl -sI -H 'Origin: https://evil.example' http://127.0.0.1:7820/ | grep -i access-control
 *
 * It must print nothing.
 *
 * ## `base: './'`
 *
 * This page is served at `/` here and framed by a host at whatever address
 * that host wrote down — behind a proxy, on another port, under a path
 * nobody here chose. Absolute asset paths are correct in the first case and a
 * guess in the second; relative ones are a fact in both, because the browser
 * resolves them against the document it just fetched.
 *
 * ## `server` keeps `cors: false` and deliberately names no port
 *
 * The port used to be demanded on the `bunx vite` line in `run.sh`, with
 * `--strictPort` behind it, so a taken 7820 stopped this app from starting at
 * all. `serves()` decides it instead, from `PREFERRED_PORT` in `manifest.ts`,
 * and it is FIRST in the plugin list because it has to claim a port before
 * anything else in this config asks for one.
 *
 * A free 7820 is taken in silence, so the `curl` line above still means what it
 * says. This app already answering there ends the start cleanly rather than
 * making a second copy of it. Anything else is a loud move to the next free
 * port, with `~/Library/Application Support/Kehikot/modules` rewritten to the port the server ACTUALLY
 * bound — read off `httpServer.address()` after `listening` rather than off what
 * was asked for, because a registration naming a port this app has drifted off
 * is one a host sweeps to find nothing.
 */
export default defineConfig({
  base: './',
  plugins: [
    serves({ id: ID, prefer: PREFERRED_PORT }),
    doors({ manifest: MANIFEST, answer, build: BUILD, ours, ancestors: [STUB_HOST], page: { title: 'References' } }),
    react(),
    tailwindcss(),
  ],
  resolve: { alias: { '@': resolve(import.meta.dirname, 'src') } },
  server: { cors: false },
})
